# Generated by Django 5.0.6 on 2024-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Imagen')),
            ],
        ),
    ]
